### PR TITLE
Password encrypted by bcryptjs

### PR DESCRIPTION
**Pull request by pankajkumarbij**
Password encrypted by bcryptjs in signup router. Now if the user stores details in the database then the password will be stored in a hashed format.
In signin router password compared by using bcyptjs. If user's password matches the database then the user will be able to login otherwise it gives an error that the email and password is not match.
Screenshot from 2020-12-07 16-05-54

### CODE REVIEW

**Comment by ankingcodes** [comment]
@pankajkumarbij - can you add the package-lock.json file to .gitignore ? Thanks.

**Comment by pankajkumarbij** [comment]
I have added the package-lock.json file to .gitignore, please review it.

**Comment by pankajkumarbij** [comment]
If anything wrong please let me know, I will correct it.

**Comment by ankingcodes** [comment]
@pankajkumarbij - Seems like you didn't create a new branch while making this PR. Anyways, I'll get this merged. Make sure you create a new branch for your next PR.

**Comment by ankingcodes** [comment]
@pankajkumarbij - Thanks for contributing !

**Pull request merged**
